version: "3"
services:
  mongo:
    container_name: tinyurlclone_mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  app:
    container_name: tinyurlclone_api
    image: node:12.16.0
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: '0.0.0.0'
      MONGO_URL: mongodb://mongo:27017/local
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run debug"
volumes:
  mongodb_data_container:
  